Description = "Weclome to Elliott's blog site that who is best on program develop, pre-sales and big data."
Keywords =  "Blog, Software, Big Data, Product, Architecture, Java, Kylin"
Subtitle = "Don't stop running forward!"
AuthorImg = "/img/author.jpg"
AuthorName = "Elliott"
Introduce = "Never forget your dreams！"
DateFormat = "2006/01/02"
YearFormat = "2006Y"
MonthFormat = "01/02"

[[Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/xx299x"

[[Socials]]
  Name = "ZhiHu"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/xu-zhi-guo-53"

[[Links]]
  Name = "Nutz"
  Permalink = "https://nutzam.com/"

[[Links]]
  Name = "JFinal"
  Permalink = "https://jfinal.com/"

[[Links]]
  Name = "Wendal"
  Permalink = "http://wendal.net/"

[[Links]]
  Name = "LiaoXueFeng"
  Permalink = "https://www.liaoxuefeng.com/"