Title =  "一品书生"
LanguageCode = "zh-CN"
BaseUrl = "https://blog.sbat.top/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "emacs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"

[Params]
  Introduce = "Programmer & Architect"
  Description = "一品书生 | 博客 | 高效工作 | Python"
  Keywords =  "一品书生,独立,博客,程序员,数据分析师,个人,思考,读书,笔记,技术,分享,管理"
  Subtitle = "生产工具决定生产效率"
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  #BaiduStatsId = "0b07433b4ab8d587dae7d34e71973839"
  #QQStatsId = "58416275"
  # RevolverMapId = "5b4f2ucxar6"
  Fancybox = true
  hasCJKLanguage = true

[Author]
  Name = "一品书生"

[Params.Share]
  #DuoShuo = "lanlingzi"
  Baidu = true

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
# [[Menu.Main]]
#   Name = "技术"
#   Pre = "code"
#   URL = "/categories/技术/"
#   Weight = 2
# [[Menu.Main]]
#   Name = "感想"
#   Pre = "tint"
#   URL = "/categories/感想/"
#   Weight = 3
# [[Menu.Main]]
#   Name = "笔记"
#   Pre = "book"
#   URL = "/categories/笔记/"
#   Weight = 4
# [[Menu.Main]]
#   Name = "杂记"
#   Pre = "leaf"
#   URL = "/categories/杂记/"
#   Weight = 5
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 6
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 7

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/xx299x"

[[Params.Socials]]
  Name = "知乎"
  Icon = "globe"
  URL = "https://www.zhihu.com/people/xu-zhi-guo-53/activities" 
[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1  
